# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('abf928d07ec9599b6df9ebd9693e04e5_MjM5MzE4MjAxMy0wNi0yMSAwMzoxOTo0MC42MTYyMTQ')
  end)
end
